      SUBROUTINE RDTABL(M,MA) 
      IMPLICIT NONE
C    COPYRIGHT 1997  WARREN P. PORTER,  ALL RIGHTS RESERVED

      REAL TD,TI

      INTEGER cons,I,I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12
      Integer IA,IB,IDIF,IEND,ILOCT,ISIZE,
     & ISTART,M,MI     

      CHARACTER*3 INAME,MA,SYMBOL

      COMMON/CARRAY/INAME(20),SYMBOL(23)
      COMMON/TABLE/ILOCT(21),TI(200),TD(200)
      COMMON/WMAIN/I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12

c     Defining console output value      
      cons = 0  

C       RDTABLE READS TABLES
C        IT ALSO CHANGES TABLES     

C     ILOCT = DATA COUNTER (# PAIRS OF TI, TD)  
C     TI = INDEPENDENT VARIABLE (TIME) OF A PAIR OF TABLE ENTRIES   
C     TD = DEPENDENT VARIABLE OF A PAIR OF TABLE ENTRIES    
C     INAME = ARRAY WITH NAMES OF TABLES (DEFINED IN BLOCK DATA)
C     MA = TABLE NAME READ FROM CONTROL CARD    
C     M = NUMBER OF PAIRS OF DATA IN A TABLE    

C    ********* BE SURE THAT THERE IS AT LEAST ONE SPACE BETWEEN *****
C    ********* ALL DATA, ESPECIALLY IF THE DEPENDENT DATA ARE NEG. **

C        CHECK TO SEE IF TABLE MA HAS BEEN PREVIOUSLY NAMED 
c    1 FORMAT(20A4)  
      DO 50 I=2,21  
      IA=I  
      IF(ILOCT(I).EQ.0) GOTO 60     
      IF(INAME(I-1).EQ.MA) GOTO 100 
   50 CONTINUE  
      WRITE(6,55) 
      WRITE(cons,55)         
   55 FORMAT('0****MORE THAN TWENTY(20) TABLES HAVE BEEN SPECIFIED.  PRO
     1GRAM TERMINATED.****')
      M=-1  
      RETURN

C     CHECK FOR MAXIMUM # OF DATA PAIRS IN ALL TABLES COLLECTIVELY  
   60 INAME(IA-1)=MA    
      ILOCT(IA)=ILOCT(IA-1)+M   
      IF(ILOCT(IA) .LE. 200) GO TO 64   
   63 FORMAT('0****THE TOTAL OF ALL TABLE ENTRIES EXCEEDS 200. PROGRAM T
     1ERMINATED.****')  
      WRITE(6,63)
      WRITE(cons,63)         
      M=-1  
      RETURN

C     READ INDEPENDENT AND DEPENDENT VARIABLE VALUES IN TABLE   
 64   M=ILOCT(IA)-1     
      MI=ILOCT(IA-1)    
c      READ (I4,*)(TI(I),TD(I),I=MI,M)    
C     ERROR CHECK FOR WRONG UNITS FOR VELOCITY
      IF (MA .EQ. 'VEL') THEN
      DO 644 I=MI,M
        IF (TD(I) .LT. 0.000) THEN
c        WRITE(0,*)'WIND SPEED ',TD(I),' APPEARS    NEGATIVE: ',
c     *      'IS THIS CORRECT?'
         ELSE
        ENDIF
644     CONTINUE
       ELSE
      CONTINUE
      ENDIF

C         CHECK TO SEE THAT THE INDEPENDENT VARIABLE IS TABLED IN ASCENDING 
C         ORDER. IF NOT, SET M LESS THAN ZERO AND RETURN.   
      M=M-1 
      DO 65 I=MI,M  
         IF(TI(I).GE.TI(I+1)) GO TO 70  
   65 CONTINUE  
C     DATA IN ASCENDING ORDER FOR THIS TABLE, QUIT  
      RETURN

C     DATA NOT IN ASCENDING ORDER   

   70 WRITE(6,71) INAME(IA-1)
      WRITE(cons,71) INAME(IA-1)   
   71 FORMAT('0  ****THE INDEPENDENT VARIABLES OF TABLE ',A3,   
     1 ' ARE NOT IN ASCENDING ORDER.  PROGRAM TERMINATED.****') 
      M=-1  
      RETURN

  100 CONTINUE  
C     MOVE TABLE UP     
C       ISTART=POINT TO START MOVING TO 
C        ISIZE=LOCATION OF FIRST MOVE POINT     
C         IEND=WHERE TO STOP
      ISIZE=ILOCT(IA)   
      ISTART=ILOCT(IA-1)
      IDIF=ISIZE-ISTART 

      DO 110 I=IA,21    
      IB=I  
      IF(ILOCT(I).EQ.0) GOTO 120    
      ILOCT(I-1)=ILOCT(I)-IDIF  
      INAME(I-1)=INAME(I)   
  110 CONTINUE  
  120 CONTINUE  
      IEND=ILOCT(IB-1)-1
      ISTART=ISTART-1
      IF(ISIZE.GT.IEND) GO TO 131   
      DO 130 I=ISIZE,IEND   
      ISTART=ISTART+1   
      TI(ISTART)=TI(I)  
      TD(ISTART)=TD(I)  
  130 CONTINUE  
  131 CONTINUE  
      IA=IB-1   

      GOTO 60   

      END   
