      SUBROUTINE JREAD(UNIT)
C    START OF READ SUBROUTINE TO DELETE # SIGNS BEFORE DATA LINES
C    THIS SUBROUTINE IMPLEMENTS THE UNIX CONVENTION OF IGNORING LINES
C    THAT START WITH #
C    NO MORE NEED TO CAREFULLY COUNT THE NUMBER OF HEADER LINES IN YOUR DATA
C    FILES. JUST START EACH HEADER LINE WITH A # , CALL JREAD WITH THE UNIT NUMBER,
C    AND JREAD WILL SKIP THEM FOR YOU. ENJOY--JIM JAEGER OCTOBER 30 2005     
      IMPLICIT NONE
       
      INTEGER UNIT
      INTEGER I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12,I91,I92,I93
     & ,I94,I95,I96  
        
      CHARACTER*1 FIRSTC
      CHARACTER*80 LABEL

      COMMON/WMAIN/I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12,I91,I92,I93
     & ,I94,I95,I96  
        
  10  CONTINUE
      READ(UNIT,20) FIRSTC,LABEL
      IF(FIRSTC.EQ.'#')THEN
c      WRITE(I2,190 )LABEL
        GOTO 10
      ENDIF
      BACKSPACE(UNIT)
 20   FORMAT(A1,1A80)
c190   FORMAT(1A80)

      END
